import { prisma } from "@/lib/prisma";

async function main() {
    let dataAvail ;

    // Seed data contoh untuk tabel cabang
    const Cabang = [ // atau personel area
        {"idBranch": "N001", "namaBranch": "ICBP-Noodle Head Office"},
        {"idBranch": "N002", "namaBranch": "ICBP-Noodle DKI"},
        {"idBranch": "N003", "namaBranch": "ICBP-Noodle Cibitung"},
        {"idBranch": "N004", "namaBranch": "ICBP-Noodle Tangerang"},
        {"idBranch": "N005", "namaBranch": "ICBP-Noodle Bandung"},
        {"idBranch": "N006", "namaBranch": "ICBP-Noodle Semarang"},
        {"idBranch": "N007", "namaBranch": "ICBP-Noodle Surabaya"},
        {"idBranch": "N008", "namaBranch": "ICBP-Noodle Medan"},
        {"idBranch": "N009", "namaBranch": "ICBP-Noodle Cirebon"},
        {"idBranch": "P001", "namaBranch": "ICBP-Noodle Pekanbaru"},
        {"idBranch": "P002", "namaBranch": "ICBP-Noodle Palembang"},
        {"idBranch": "P003", "namaBranch": "ICBP-Noodle Lampung"},
        {"idBranch": "P004", "namaBranch": "ICBP-Noodle Banjarmasin"},
        {"idBranch": "P005", "namaBranch": "ICBP-Noodle Pontianak"},
        {"idBranch": "P006", "namaBranch": "ICBP-Noodle Manado"},
        {"idBranch": "P007", "namaBranch": "ICBP-Noodle Makassar"},
        {"idBranch": "P008", "namaBranch": "ICBP-Noodle Jambi"},
        {"idBranch": "P009", "namaBranch": "ICBP-Noodle Tj. Api Api"},
    ]
    for (let i = 0; i < Cabang.length; i++) {
        await prisma.dataBranch.upsert(
            {
                where: { idBranch : Cabang[i]["idBranch"] },
                update: {},
                create: { idBranch : Cabang[i]["idBranch"], namaBranch : Cabang[i]["namaBranch"]},
            }
        )        
    }



    const Department = [ // atau pers subarea 
        {"idDepartment": "ADM-FA", "namaDepartment": "ADM Fin.& Acct."},
        {"idDepartment": "ADM-GM", "namaDepartment": "ADM Gen.Mgt"},
        {"idDepartment": "ADM-HR", "namaDepartment": "ADM HR"},
        {"idDepartment": "MFG-MFT", "namaDepartment": "MFG Manufactur"},
        {"idDepartment": "MFG-PPIC", "namaDepartment": "MFG PPIC"},
        {"idDepartment": "MFG-PROD", "namaDepartment": "MFG Production"},
        {"idDepartment": "MFG-PURC", "namaDepartment": "MFG Purchasing"},
        {"idDepartment": "MFG-TECH", "namaDepartment": "MFG Technical"},
        {"idDepartment": "MFG-WRH", "namaDepartment": "MFG Warehouse"},
        {"idDepartment": "MKT-MKT", "namaDepartment": "MKT Marketing"},
        {"idDepartment": "MKT-SD", "namaDepartment": "MKT Sales&Distr"},
        {"idDepartment": "RND-QCA", "namaDepartment": "R&D QC/QA"},
        {"idDepartment": "RND-RD", "namaDepartment": "R&D Resrch.Dev."},
    ]
    for (let i = 0; i < Department.length; i++) {
        await prisma.dataDepartment.upsert(
            {
                where: { idDepartment : Department[i]["idDepartment"] },
                update: {},
                create: { idDepartment : Department[i]["idDepartment"], namaDepartment : Department[i]["namaDepartment"]},
            }
        )        
    }
    
    const levelPosition = [
        {"idLevel": "opr", "namaLevel": "Operational"},
        {"idLevel": "staff", "namaLevel": "Staff"},
        {"idLevel": "spv", "namaLevel": "Supervisor"},
        {"idLevel": "mgr", "namaLevel": "Manager"},
    ]
    for (let i = 0; i < levelPosition.length; i++) {
        await prisma.dataLevel.upsert(
            {
                where: { idLevel : levelPosition[i]["idLevel"] },
                update: {},
                create: { idLevel : levelPosition[i]["idLevel"], namaLevel : levelPosition[i]["namaLevel"]},
            }
        )        
    }
    
    const Position = [
        {"namaPosition": "A & P Admin", "department": "MKT-MKT"},
        {"namaPosition": "A & P Coord", "department": "MKT-MKT"},
        {"namaPosition": "A & P Spv", "department": "MKT-MKT"},
        {"namaPosition": "A & P Staff", "department": "MKT-MKT"},
        {"namaPosition": "Acct Spv", "department": "ADM-FA"},
        {"namaPosition": "Acct Staff", "department": "ADM-FA"},
        {"namaPosition": "Admin to ASPM", "department": "MKT-MKT"},
        {"namaPosition": "Admin to BHRM", "department": "ADM-HR"},
        {"namaPosition": "Admin to BPDQC Mgr", "department": "RND-QCA"},
        {"namaPosition": "Admin to Fin & Acct Mgr", "department": "ADM-FA"},
        {"namaPosition": "Admin to FM", "department": "MFG-PROD"},
        {"namaPosition": "Admin to PM", "department": "MFG-PROD"},
        {"namaPosition": "Admin to Whs Mgr", "department": "MFG-WRH"},
        {"namaPosition": "Area Sales & Promotion Mgr, Act", "department": "MKT-SD"},
        {"namaPosition": "Area Sales & Promotion Repr", "department": "MKT-SD"},
        {"namaPosition": "Area Sales & Promotion Repr, Act", "department": "MKT-SD"},
        {"namaPosition": "Area Sales & Promotion Spv", "department": "MKT-SD"},
        {"namaPosition": "Area Sales & Promotion Spv, Act", "department": "MKT-SD"},
        {"namaPosition": "Assistant BM Indomie", "department": "MKT-MKT"},
        {"namaPosition": "Bag Noodle Dev Spv", "department": "RND-RD"},
        {"namaPosition": "BPDQC Mgr, Act", "department": "RND-QCA"},
        {"namaPosition": "BPDQC Spv", "department": "RND-QCA"},
        {"namaPosition": "Branch HR Mgr, Act", "department": "ADM-HR"},
        {"namaPosition": "Branch HR Officer", "department": "ADM-HR"},
        {"namaPosition": "Budget & Controller Spv", "department": "ADM-FA"},
        {"namaPosition": "Budget & Controller Spv, Act", "department": "ADM-FA"},
        {"namaPosition": "Buyer", "department": "MFG-PURC"},
        {"namaPosition": "Cashier", "department": "ADM-FA"},
        {"namaPosition": "Category Management Specialist", "department": "MKT-SD"},
        {"namaPosition": "Central Doc Control Spv", "department": "RND-QCA"},
        {"namaPosition": "Chemical Analyst", "department": "RND-QCA"},
        {"namaPosition": "Comben Assistant", "department": "ADM-HR"},
        {"namaPosition": "Comben Spv", "department": "ADM-HR"},
        {"namaPosition": "Comben Spv, Act", "department": "ADM-HR"},
        {"namaPosition": "Comben Staff", "department": "ADM-HR"},
        {"namaPosition": "Continous Improvement Spv", "department": "ADM-HR"},
        {"namaPosition": "Coord Ingr. & Alkali", "department": "MFG-PROD"},
        {"namaPosition": "Cost & Finance Spv", "department": "ADM-FA"},
        {"namaPosition": "Cost Acct Spv", "department": "ADM-FA"},
        {"namaPosition": "Cost Acct Staff", "department": "ADM-FA"},
        {"namaPosition": "CQA & CQC Admin", "department": "RND-QCA"},
        {"namaPosition": "Cup Noodle & RM Dev Spv", "department": "RND-RD"},
        {"namaPosition": "Distribution Admin", "department": "MKT-SD"},
        {"namaPosition": "Distribution Assistant", "department": "MKT-SD"},
        {"namaPosition": "Distribution Officer", "department": "MKT-SD"},
        {"namaPosition": "Distribution Officer, Act", "department": "MKT-SD"},
        {"namaPosition": "Distribution Staff", "department": "MKT-SD"},
        {"namaPosition": "Doc Controller Spv", "department": "ADM-GM"},
        {"namaPosition": "Doc Controller Staff", "department": "ADM-GM"},
        {"namaPosition": "Draft & Design Sect Spv", "department": "MFG-TECH"},
        {"namaPosition": "Electrical Technical Spv", "department": "MFG-TECH"},
        {"namaPosition": "Employee Service Staff", "department": "ADM-HR"},
        {"namaPosition": "Fin & Acct Mgr, Act", "department": "ADM-FA"},
        {"namaPosition": "Finance Spv", "department": "ADM-FA"},
        {"namaPosition": "Finance Staff", "department": "ADM-FA"},
        {"namaPosition": "Flavour Dev Technician", "department": "RND-RD"},
        {"namaPosition": "Flavour Engineering & Dev Spv", "department": "RND-RD"},
        {"namaPosition": "Food Services Spv", "department": "MKT-SD"},
        {"namaPosition": "GAS Assistant", "department": "ADM-HR"},
        {"namaPosition": "GAS Coord", "department": "ADM-HR"},
        {"namaPosition": "GAS Spv", "department": "ADM-HR"},
        {"namaPosition": "GAS Spv, Act", "department": "ADM-HR"},
        {"namaPosition": "GAS Staff", "department": "ADM-HR"},
        {"namaPosition": "General Acct Spv", "department": "ADM-FA"},
        {"namaPosition": "General Acct Staff", "department": "ADM-FA"},
        {"namaPosition": "Halal Coord & Customer Complain Spv", "department": "ADM-HR"},
        {"namaPosition": "HCO EDP Spv", "department": "MKT-SD"},
        {"namaPosition": "HCO Spv", "department": "MKT-SD"},
        {"namaPosition": "HR Admin", "department": "ADM-HR"},
        {"namaPosition": "HR Admin Spv", "department": "ADM-HR"},
        {"namaPosition": "HR EDP Staff", "department": "ADM-HR"},
        {"namaPosition": "HRIS & Comben Spv", "department": "ADM-HR"},
        {"namaPosition": "HRIS Spv", "department": "ADM-HR"},
        {"namaPosition": "Indomie Brand Admin", "department": "MKT-MKT"},
        {"namaPosition": "Instrument Analyst", "department": "RND-QCA"},
        {"namaPosition": "IR & PR Asst", "department": "ADM-HR"},
        {"namaPosition": "IR & PR Spv", "department": "ADM-HR"},
        {"namaPosition": "IR & PR Staff", "department": "ADM-HR"},
        {"namaPosition": "IR Assistant", "department": "ADM-HR"},
        {"namaPosition": "IR Spv", "department": "ADM-HR"},
        {"namaPosition": "IR Staff", "department": "ADM-HR"},
        {"namaPosition": "Key Account Spv", "department": "MKT-SD"},
        {"namaPosition": "Key Account Spv E-Commerce", "department": "MKT-SD"},
        {"namaPosition": "Key Account Spv Modern Food Service", "department": "MKT-SD"},
        {"namaPosition": "Key Account Spv MTKA", "department": "MKT-SD"},
        {"namaPosition": "Lab Chemistry Coordinator", "department": "RND-QCA"},
        {"namaPosition": "Lab Microbiology Coordinator", "department": "RND-QCA"},
        {"namaPosition": "Management EDP Spv", "department": "ADM-GM"},
        {"namaPosition": "Management EDP Spv, Act", "department": "ADM-GM"},
        {"namaPosition": "Management EDP Staff", "department": "ADM-GM"},
        {"namaPosition": "Manpower Productivity Spv", "department": "ADM-HR"},
        {"namaPosition": "Marketing Admin", "department": "MKT-MKT"},
        {"namaPosition": "Marketing EDP Spv", "department": "MKT-SD"},
        {"namaPosition": "Marketing EDP Spv", "department": "MKT-MKT"},
        {"namaPosition": "Marketing EDP Spv, Act", "department": "MKT-MKT"},
        {"namaPosition": "Marketing EDP Staff", "department": "MKT-MKT"},
        {"namaPosition": "Microbiology Analyst", "department": "RND-QCA"},
        {"namaPosition": "Modern Trade Promotion Analyst & Support", "department": "MKT-SD"},
        {"namaPosition": "MT Acct", "department": "ADM-HR"},
        {"namaPosition": "MT HR", "department": "ADM-HR"},
        {"namaPosition": "MT MFG", "department": "ADM-HR"},
        {"namaPosition": "MT PPIC", "department": "ADM-HR"},
        {"namaPosition": "MT Sales", "department": "ADM-HR"},
        {"namaPosition": "Nd Others, Shelf Life & Regulatory Staff", "department": "RND-RD"},
        {"namaPosition": "NPL Project & Shelf Life Spv", "department": "RND-QCA"},
        {"namaPosition": "OD & PD Staff", "department": "ADM-HR"},
        {"namaPosition": "Operation Dev Spv", "department": "MFG-MFT"},
        {"namaPosition": "Org Dev Spv", "department": "ADM-HR"},
        {"namaPosition": "Org Dev Spv, Act", "department": "ADM-HR"},
        {"namaPosition": "Org Dev Staff", "department": "ADM-HR"},
        {"namaPosition": "Panel Dev Staff", "department": "RND-RD"},
        {"namaPosition": "Panelis Dev Coordinator", "department": "RND-RD"},
        {"namaPosition": "People Dev Staff", "department": "ADM-HR"},
        {"namaPosition": "PPIC Assistant", "department": "MFG-PPIC"},
        {"namaPosition": "PPIC RM Planning Assistant", "department": "MFG-PPIC"},
        {"namaPosition": "PPIC RM Planning Staff", "department": "MFG-PPIC"},
        {"namaPosition": "PPIC Spv", "department": "MFG-PPIC"},
        {"namaPosition": "PPIC Spv, Act", "department": "MFG-PPIC"},
        {"namaPosition": "PPIC Staff", "department": "MFG-PPIC"},
        {"namaPosition": "PR Staff", "department": "ADM-HR"},
        {"namaPosition": "Prod EPS Section Spv", "department": "MFG-PROD"},
        {"namaPosition": "Prod EPS Spv", "department": "MFG-PROD"},
        {"namaPosition": "Prod Section SILO", "department": "MFG-PROD"},
        {"namaPosition": "Prod Section Spv", "department": "MFG-PROD"},
        {"namaPosition": "Prod Section Spv, Act", "department": "MFG-PROD"},
        {"namaPosition": "Prod Shift Spv", "department": "MFG-PROD"},
        {"namaPosition": "Prod Shift Spv, Act", "department": "MFG-PROD"},
        {"namaPosition": "Product Dev Technician", "department": "RND-RD"},
        {"namaPosition": "Production Mgr, Act", "department": "MFG-PROD"},
        {"namaPosition": "Production Spv", "department": "MFG-PROD"},
        {"namaPosition": "Prototype Technician", "department": "RND-RD"},
        {"namaPosition": "Proximat Analyst", "department": "RND-QCA"},
        {"namaPosition": "Purchasing Admin", "department": "MFG-PURC"},
        {"namaPosition": "Purchasing Assistant", "department": "MFG-PURC"},
        {"namaPosition": "Purchasing Officer", "department": "MFG-PURC"},
        {"namaPosition": "Purchasing Staff", "department": "MFG-PURC"},
        {"namaPosition": "QC Auditor Spv", "department": "RND-QCA"},
        {"namaPosition": "QC FG Section Spv", "department": "RND-QCA"},
        {"namaPosition": "QC FG Section Spv, Act", "department": "RND-QCA"},
        {"namaPosition": "QC PD Section Spv", "department": "RND-QCA"},
        {"namaPosition": "QC PD Spv", "department": "RND-QCA"},
        {"namaPosition": "QC Process Section Spv", "department": "RND-QCA"},
        {"namaPosition": "QC Process Spv", "department": "RND-QCA"},
        {"namaPosition": "QC Process Spv, Act", "department": "RND-QCA"},
        {"namaPosition": "QC RM & FG Section Spv", "department": "RND-QCA"},
        {"namaPosition": "QC RM & FG Spv", "department": "RND-QCA"},
        {"namaPosition": "QC RM & FG Spv, Act", "department": "RND-QCA"},
        {"namaPosition": "QC RM Section Spv", "department": "RND-QCA"},
        {"namaPosition": "QC Section Spv", "department": "RND-QCA"},
        {"namaPosition": "Sales EDP Spv", "department": "MKT-SD"},
        {"namaPosition": "Sales Trainee", "department": "ADM-HR"},
        {"namaPosition": "Sales Trainee - ASPR, Act", "department": "ADM-HR"},
        {"namaPosition": "Sarimi Brand Admin", "department": "MKT-MKT"},
        {"namaPosition": "Secretary to BM", "department": "ADM-GM"},
        {"namaPosition": "Secretary to Div. Head", "department": "ADM-GM"},
        {"namaPosition": "Secretary to GM", "department": "ADM-GM"},
        {"namaPosition": "Secretary to GM Fin & Acct", "department": "ADM-FA"},
        {"namaPosition": "Secretary to GM HR", "department": "ADM-HR"},
        {"namaPosition": "Secretary to GM Marketing", "department": "MKT-MKT"},
        {"namaPosition": "Secretary to GM Mfg", "department": "MFG-MFT"},
        {"namaPosition": "Secretary to GM Sales", "department": "MKT-SD"},
        {"namaPosition": "Section Whs Spare Part", "department": "MFG-TECH"},
        {"namaPosition": "Security Chief", "department": "ADM-HR"},
        {"namaPosition": "Security Grp Leader", "department": "ADM-HR"},
        {"namaPosition": "SHE Assistant", "department": "ADM-HR"},
        {"namaPosition": "SHE Spv", "department": "ADM-HR"},
        {"namaPosition": "SHE Staff", "department": "ADM-HR"},
        {"namaPosition": "System Analyst Spv", "department": "ADM-FA"},
        {"namaPosition": "Targeted Flavour Dev Spv", "department": "RND-RD"},
        {"namaPosition": "Targeted Flavour Dev Staff", "department": "RND-RD"},
        {"namaPosition": "Tax & Acct Spv", "department": "ADM-FA"},
        {"namaPosition": "Tax Officer", "department": "ADM-FA"},
        {"namaPosition": "Tax Staff", "department": "ADM-FA"},
        {"namaPosition": "Tech Building & General Sec", "department": "MFG-TECH"},
        {"namaPosition": "Tech EPS Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech PM Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Process Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Prod EPS Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Prod Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Prod Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Utility Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Utility Spv", "department": "MFG-TECH"},
        {"namaPosition": "Tech Workshop Section", "department": "MFG-TECH"},
        {"namaPosition": "Tech Workshop Section Spv", "department": "MFG-TECH"},
        {"namaPosition": "Technical Mgr, Act", "department": "MFG-TECH"},
        {"namaPosition": "Technical Spv", "department": "MFG-TECH"},
        {"namaPosition": "Trade Marketing Spv GT", "department": "MKT-SD"},
        {"namaPosition": "Trade Marketing Spv MTI", "department": "MKT-SD"},
        {"namaPosition": "Warehouse FG Spv", "department": "MFG-WRH"},
        {"namaPosition": "Warehouse Mgr, Act", "department": "MFG-WRH"},
        {"namaPosition": "Warehouse Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs FG Section Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs FG Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs RM Admin", "department": "MFG-WRH"},
        {"namaPosition": "Whs RM Section Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs RM Section Spv, Act", "department": "MFG-WRH"},
        {"namaPosition": "Whs RM Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs RM Spv, Act", "department": "MFG-WRH"},
        {"namaPosition": "Whs SP & A&P Section Spv", "department": "MFG-WRH"},
        {"namaPosition": "Whs SP Section Spv", "department": "MFG-WRH"},
        {"namaPosition": "Workshop Supervisor", "department": "MFG-TECH"}
    ]
    for (let index = 0; index < Position.length; index++) {
        await prisma.dataPosition.upsert(
            {
                where: { namaPosition : Position[index]["namaPosition"] },
                update: {},
                create: { namaPosition : Position[index]["namaPosition"] },
            }
        )
    }

console.log('Done seeding!');
}

main()
.catch((e) => {
    console.error(e);
    process.exit(1);
})
.finally(async () => {
    return null;
});
